name: Deploy Day 7

on:
  push:
    branches:
      - master

jobs:
  build-day7:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./day7
    steps:
      - uses: actions/checkout@v2
      - shell: bash
        run: |
          ls -lah
          curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
          heroku --version
          git config --global user.email ${{secrets.HEROKU_EMAIL}}
          git config --global user.name ${{secrets.HEROKU_NAME}}
          git config --global init.defaultBranch master
          git init && git add . && git commit -m "deploy to heroku"
          git remote add day7 https://git.heroku.com/${{secrets.HEROKU_PROJECT_DAY7_NAME}}.git
          export HEROKU_API_KEY="${{secrets.HEROKU_API_TOKEN}}"
          git push day7 master --force
